-- Seed D1 with what the vault already holds, so the UNIQUE (term, kind)
-- constraint can do the duplicate check against the whole vocabulary
-- rather than only against what came in through capture.
INSERT INTO item (term, kind, meaning, vi, ipa, cefr, status, source, created_at, updated_at)
VALUES
('I''m not following','conversational','a softer way of saying "I don''t understand"','tôi chưa theo kịp',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('abide by','phrasal-verb','to accept or act in accordance with a rule, decision, or recommendation','tuân theo, chấp hành',NULL,'c2','published','vault',datetime('now'),datetime('now')),
('according to','conversational','as stated by a source','theo như (nguồn nào đó)',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('accuse','word','to say that somebody has done something wrong or is guilty of something','buộc tội, cáo buộc','/əˈkjuːz/','b2','published','vault',datetime('now'),datetime('now')),
('adequate','word','enough in quantity, or good enough in quality, for a particular purpose','đủ (ở mức chấp nhận được), tạm ổn','/ˈædɪkwət/','b2','published','vault',datetime('now'),datetime('now')),
('aggregate','word','the total; everything added together','tổng gộp','/ˈæɡrɪɡət/','b2','published','vault',datetime('now'),datetime('now')),
('amenity','word','a desirable or useful feature or facility of a building or place','tiện ích, tiện nghi','/əˈmiːnəti/',NULL,'published','vault',datetime('now'),datetime('now')),
('antitrust','word','(of laws) preventing companies from controlling prices unfairly','chống độc quyền','/ˌæntiˈtrʌst/','c1','published','vault',datetime('now'),datetime('now')),
('apocalypse','word','the end of the world','tận thế','/əˈpɒkəlɪps/','b2','published','vault',datetime('now'),datetime('now')),
('apocalyptic','word','disaster-like; used loosely for anything extreme','như tận thế; cực kỳ thảm khốc','/əˌpɒkəˈlɪptɪk/','c1','published','vault',datetime('now'),datetime('now')),
('an architectural decision','collocation','a decision about the fundamental structure of a system, expensive to reverse later','quyết định kiến trúc (khó đảo ngược)','architectural /ˌɑːkɪˈtektʃərəl/','c1','published','vault',datetime('now'),datetime('now')),
('as I understand it','conversational','this is my understanding, and I may be wrong','theo như tôi hiểu',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('ask someone about something','collocation','the preposition frame for *ask*','hỏi ai đó về việc gì',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('asset','word','a useful or valuable quality, person, or thing','tài sản, thế mạnh','/ˈæset/','b2','published','vault',datetime('now'),datetime('now')),
('awareness of','collocation','knowledge or perception of a situation or fact','nhận thức về','/əˈweənəs/','b2','published','vault',datetime('now'),datetime('now')),
('awe','word','a feeling of respect and slight fear, or of being very impressed','sự nể phục pha chút choáng ngợp, kính sợ','/ɔː/','b2','published','vault',datetime('now'),datetime('now')),
('bacteria','word','the simplest and smallest forms of life, often a cause of disease','vi khuẩn (số nhiều; số ít là *bacterium*)','/bækˈtɪəriə/','b2','published','vault',datetime('now'),datetime('now')),
('barley','word','a plant grown for its grain, used for making food, beer and whisky','lúa mạch','/ˈbɑːli/','c1','published','vault',datetime('now'),datetime('now')),
('beyond reason / past reason','idiom','past the point where logic applies','vượt quá lý trí',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('blast radius','word','(computing) how much of a system is affected when one part fails','phạm vi ảnh hưởng khi một thành phần hỏng','/ˌblɑːst ˈreɪdiəs/','c1','published','vault',datetime('now'),datetime('now')),
('blocked','word','obstructed so as to prevent flow or passage','bị tắc nghẽn, bị chặn',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('brittle','word','hard but easily broken','giòn, dễ vỡ; (nghĩa bóng) mong manh, dễ gãy','/ˈbrɪtl/','c1','published','vault',datetime('now'),datetime('now')),
('buggy','word','(computing) containing many errors; (Oxford) a small light vehicle','(phần mềm) đầy lỗi; (nghĩa từ điển) xe nhỏ không mui','/ˈbʌɡi/','c1','published','vault',datetime('now'),datetime('now')),
('build out','phrasal-verb','to expand something into a fuller, more complete version','xây dựng mở rộng, hoàn thiện dần','/ˌbɪld ˈaʊt/','b2','published','vault',datetime('now'),datetime('now')),
('capsule','word','the foil or plastic sleeve over the cork of a bottle','nắp bọc cổ chai; (nghĩa thường gặp) viên nang thuốc','/ˈkæpsjuːl/','c1','published','vault',datetime('now'),datetime('now')),
('cede ground','idiom','to give up an advantage or a position to a rival','nhường lợi thế, mất vị thế vào tay đối thủ','cede /siːd/','c1','published','vault',datetime('now'),datetime('now')),
('a chorus of','idiom','the sound of a lot of people expressing approval or disapproval at the same time','một loạt tiếng nói đồng thanh (khen hoặc chê)','chorus /ˈkɔːrəs/','c1','published','vault',datetime('now'),datetime('now')),
('the clear / early front-runner','collocation','adjectives that naturally go with *front-runner*','ứng viên dẫn đầu rõ rệt / từ sớm',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('come across','phrasal-verb','to find or meet by chance','tình cờ gặp/thấy','/ˌkʌm əˈkrɒs/','b2','published','vault',datetime('now'),datetime('now')),
('concentrated','word','made stronger because water or other substances have been removed','cô đặc; (nghĩa khác) tập trung cao độ','/ˈkɒnsntreɪtɪd/','b2','published','vault',datetime('now'),datetime('now')),
('congested','word','extremely crowded and blocked with traffic or people','bị tắc nghẽn giao thông','/kənˈdʒestɪd/',NULL,'published','vault',datetime('now'),datetime('now')),
('congestion','word','the state of being extremely crowded or blocked (especially traffic)','sự tắc nghẽn giao thông','/kənˈdʒestʃən/',NULL,'published','vault',datetime('now'),datetime('now')),
('contender','word','a serious competitor','đối thủ nặng ký','/kənˈtendə/','b2','published','vault',datetime('now'),datetime('now')),
('cork','word','the stopper of a bottle; the soft bark of a Mediterranean oak it is made from','nút bần; gỗ bần','/kɔːk/','c2','published','vault',datetime('now'),datetime('now')),
('a counterculture figure / movement / icon','collocation','nouns that naturally follow *counterculture*','nhân vật/phong trào/biểu tượng phản văn hoá',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('counterculture','word','a culture that opposes the mainstream','phản văn hoá','/ˈkaʊntəkʌltʃə/','c1','published','vault',datetime('now'),datetime('now')),
('counterintuitive','word','true, but it feels wrong at first','phản trực giác','/ˌkaʊntərɪnˈtjuːɪtɪv/','c1','published','vault',datetime('now'),datetime('now')),
('counterproductive','word','achieving the opposite of what you wanted','phản tác dụng','/ˌkaʊntəprəˈdʌktɪv/','b2','published','vault',datetime('now'),datetime('now')),
('crunch','word','three senses — see below','tuỳ nghĩa (xem bên dưới)','/krʌntʃ/','c2','published','vault',datetime('now'),datetime('now')),
('cure','word','two unrelated senses — see below','tuỳ nghĩa (xem bên dưới)','/kjʊə(r)/','b2','published','vault',datetime('now'),datetime('now')),
('a dark horse','idiom','an unknown who does surprisingly well','ngựa ô; ẩn số gây bất ngờ',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('deftly','word','in a way that shows skill; with quick, skilful movements','một cách khéo léo, gọn gàng','/ˈdeftli/','c2','published','vault',datetime('now'),datetime('now')),
('degrade','word','to make something worse in quality; to treat somebody without respect','làm suy giảm chất lượng; hạ thấp phẩm giá ai đó','/dɪˈɡreɪd/','c1','published','vault',datetime('now'),datetime('now')),
('deliberate','word','two words in one spelling — see below','tuỳ nghĩa (xem bên dưới)','adj /dɪˈlɪbərət/ · verb /dɪˈlɪbəreɪt/','b2','published','vault',datetime('now'),datetime('now')),
('devotion','word','great love and care for somebody, or the giving of a lot of time and energy to something','sự tận tuỵ, lòng tận tâm; lòng sùng kính (tôn giáo)','/dɪˈvəʊʃn/','c1','published','vault',datetime('now'),datetime('now')),
('disingenuous','word','not sincere, especially when you pretend to know less about something than you really do','giả vờ thành thật; thiếu chân thành','/ˌdɪsɪnˈdʒenjuəs/','c1','published','vault',datetime('now'),datetime('now')),
('dissolve','word','(of a solid) to mix into a liquid and become part of it','hoà tan','/dɪˈzɒlv/','c1','published','vault',datetime('now'),datetime('now')),
('doctrinaire','word','rigidly following doctrine, regardless of the facts','giáo điều','/ˌdɒktrɪˈneə/','c1','published','vault',datetime('now'),datetime('now')),
('doomer','word','someone who believes the future will be catastrophic','người bi quan tận thế','/ˈduːmə(r)/','c1','published','vault',datetime('now'),datetime('now')),
('doomsday','word','the end of the world; (informal) a very long time','ngày tận thế; (thân mật) lâu vô tận','/ˈduːmzdeɪ/','c2','published','vault',datetime('now'),datetime('now')),
('echo','word','to repeat an idea or opinion because you agree with it','lặp lại, cộng hưởng (ý kiến của ai)','/ˈekəʊ/','c1','published','vault',datetime('now'),datetime('now')),
('efficiency','word','output per unit of input','hiệu suất','/ɪˈfɪʃnsi/','b1','published','vault',datetime('now'),datetime('now')),
('elasticity','word','how strongly demand responds to a change in price','độ co giãn (của cầu)','/ˌiːlæˈstɪsəti/','c1','published','vault',datetime('now'),datetime('now')),
('emerge as','collocation','to become recognised as something over time','dần trở thành, nổi lên như là','/ɪˈmɜːdʒ əz/','b2','published','vault',datetime('now'),datetime('now')),
('enforce','word','to make sure that people obey a particular law or rule','thực thi, cưỡng chế (luật, quy tắc)','/ɪnˈfɔːs/','c1','published','vault',datetime('now'),datetime('now')),
('enigma','word','a mysterious person','người bí ẩn','/ɪˈnɪɡmə/','c1','published','vault',datetime('now'),datetime('now')),
('equivalent','word','a matching word or thing','từ/vật tương đương','/ɪˈkwɪvələnt/','b2','published','vault',datetime('now'),datetime('now')),
('era','word','a historical period','kỷ nguyên','/ˈɪərə/','b1','published','vault',datetime('now'),datetime('now')),
('fanatic','word','someone extreme about a cause','kẻ cuồng tín','/fəˈnætɪk/','b2','published','vault',datetime('now'),datetime('now')),
('feat','word','an action or piece of work that needs skill, strength or courage','kỳ tích, thành tựu đáng nể','/fiːt/','c1','published','vault',datetime('now'),datetime('now')),
('fend off','phrasal-verb','to defend yourself against something attacking you; to hold off difficult questions or problems','chống đỡ, gạt đi, cầm cự','/ˌfend ˈɒf/','c1','published','vault',datetime('now'),datetime('now')),
('fine','word','a sum of money exacted as a penalty for an offense, or to punish someone by making them pay this','tiền phạt / phạt tiền','/faɪn/','c1','published','vault',datetime('now'),datetime('now')),
('a first-order concern / a second-order concern','collocation','a first-order concern is the most important one; a second-order concern is a knock-on effect','mối quan tâm hàng đầu / thứ cấp',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('free up','phrasal-verb','to release something for other use','giải phóng (tài nguyên)','/ˌfriː ˈʌp/','b2','published','vault',datetime('now'),datetime('now')),
('from underdog to front-runner','idiom','a rise from expected loser to leader','từ kẻ yếu thế thành người dẫn đầu',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('front-runner','word','the one currently leading','người dẫn đầu','/ˈfrʌnt ˌrʌnə/','b2','published','vault',datetime('now'),datetime('now')),
('frontier','word','the limit of what is known in a subject; also a border between countries','ranh giới tri thức/công nghệ; biên giới','/ˈfrʌntɪə(r)/','c1','published','vault',datetime('now'),datetime('now')),
('germinate','word','(of a seed) to start to grow','nảy mầm','/ˈdʒɜːmɪneɪt/','b2','published','vault',datetime('now'),datetime('now')),
('go ahead','phrasal-verb','three senses — see below','tuỳ nghĩa (xem bên dưới)','/ˌɡəʊ əˈhed/','b1','published','vault',datetime('now'),datetime('now')),
('go everywhere easily','collocation','to travel or move around to all places without difficulty','đi lại khắp nơi một cách dễ dàng',NULL,NULL,'published','vault',datetime('now'),datetime('now')),
('go off on a tangent','idiom','to drift off topic','lạc đề','tangent /ˈtændʒənt/','c1','published','vault',datetime('now'),datetime('now')),
('go off the rails','idiom','to lose control of your life','đi chệch hướng; mất kiểm soát',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('go off','phrasal-verb','six distinct senses — see below','tuỳ nghĩa (xem bên dưới)','/ˌɡəʊ ˈɒf/','b2','published','vault',datetime('now'),datetime('now')),
('grain','word','the small, hard seeds of food plants such as barley, wheat or rice','hạt ngũ cốc; hạt nhỏ li ti (cát, muối)','/ɡreɪn/','b1','published','vault',datetime('now'),datetime('now')),
('grist','word','grain that has been milled ready for mashing; (figurative) useful material','bột/hạt đã nghiền; (nghĩa bóng) chất liệu hữu ích','/ɡrɪst/','b2','published','vault',datetime('now'),datetime('now')),
('hand in your notice','idiom','to resign formally','nộp đơn xin nghỉ việc',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('a handful of','collocation','a small, imprecise number of things — roughly a few','một số ít, vài (không chính xác)','/ˈhændfʊl/','c1','published','vault',datetime('now'),datetime('now')),
('heat conductor','collocation','a substance that lets heat pass through it','vật dẫn nhiệt','/ˌhiːt kənˈdʌktə(r)/','c1','published','vault',datetime('now'),datetime('now')),
('hinder','word','to make it difficult for somebody to do something or for something to happen','cản trở, gây khó khăn','/ˈhɪndə(r)/','b2','published','vault',datetime('now'),datetime('now')),
('human resources','collocation','the people side of an organisation; the HR department','nhân sự',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('hypocrite','word','someone who says one thing and does another','kẻ đạo đức giả','/ˈhɪpəkrɪt/','b2','published','vault',datetime('now'),datetime('now')),
('ideological','word','driven by doctrine rather than evidence','mang tính ý thức hệ; giáo điều','/ˌaɪdiəˈlɒdʒɪkl/','c1','published','vault',datetime('now'),datetime('now')),
('if anything','conversational','in fact, the opposite is true','thậm chí ngược lại',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('in aggregate','conversational','when everything is added together','tính tổng lại',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('in order of priority','collocation','ranked from most to least important','theo thứ tự ưu tiên',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('incursion','word','a sudden attack on a place by foreign forces; an unwanted appearance of something in an area','cuộc xâm nhập, sự lấn vào','/ɪnˈkɜːʃn/','c1','published','vault',datetime('now'),datetime('now')),
('infeasible','word','not possible to do or achieve','bất khả thi','/ɪnˈfiːzəbl/','c1','published','vault',datetime('now'),datetime('now')),
('intervention','word','action taken to improve or help a situation','sự can thiệp','/ˌɪntəˈvenʃn/','c1','published','vault',datetime('now'),datetime('now')),
('it stands to reason','idiom','it is logical; it follows naturally','lẽ dĩ nhiên; hợp lý thôi',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('law-abiding','word','obedient to the laws of society','tuân thủ pháp luật','/ˈlɔː əbaɪdɪŋ/',NULL,'published','vault',datetime('now'),datetime('now')),
('leapfrog','phrasal-verb','to jump ahead of a competitor','vượt mặt','/ˈliːpfrɒɡ/','c1','published','vault',datetime('now'),datetime('now')),
('levy','word','(verb) to demand and collect a tax by official authority; (noun) the amount demanded','đánh thuế, thu (khoản bắt buộc); khoản thu, thuế','/ˈlevi/','c1','published','vault',datetime('now'),datetime('now')),
('liability','word','a person or thing whose presence or behavior is likely to cause embarrassment or disadvantage','gánh nặng, khoản nợ, nghĩa vụ pháp lý','/ˌlaɪəˈbɪləti/',NULL,'published','vault',datetime('now'),datetime('now')),
('long-term retention','conversational','keeping something in memory over a long period','ghi nhớ lâu dài',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('lunatic','word','a madman','kẻ điên','/ˈluːnətɪk/','b2','published','vault',datetime('now'),datetime('now')),
('mainstream','word','the dominant, conventional culture','dòng chính','/ˈmeɪnstriːm/','b2','published','vault',datetime('now'),datetime('now')),
('make something stick','idiom','to make something stay in memory','làm cho nhớ lâu',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('make up','phrasal-verb','to invent a story or excuse, especially in order to deceive','bịa ra (câu chuyện, lý do)','/ˌmeɪk ˈʌp/','b1','published','vault',datetime('now'),datetime('now')),
('malt','word','grain, usually barley, that has been left in water for a time and then dried, used for making beer and whisky','mạch nha (lúa mạch đã ngâm, nảy mầm rồi sấy khô)','/mɔːlt/','c2','published','vault',datetime('now'),datetime('now')),
('mash','word','a mixture of malt grains and hot water, used for making beer and whisky','hỗn hợp mạch nha nghiền với nước nóng; (động từ) nghiền nhuyễn','/mæʃ/','c1','published','vault',datetime('now'),datetime('now')),
('massive scale','collocation','a very large size of operation','quy mô rất lớn','/ˌmæsɪv ˈskeɪl/','b2','published','vault',datetime('now'),datetime('now')),
('mission-critical','word','essential for an organization to function successfully','trọng yếu, không thể thiếu (với hoạt động của tổ chức)','/ˌmɪʃn ˈkrɪtɪkl/','c1','published','vault',datetime('now'),datetime('now')),
('move on','phrasal-verb','to leave a job (vague and polite)','chuyển việc (nói giảm)','/ˌmuːv ˈɒn/','b2','published','vault',datetime('now'),datetime('now')),
('multi-tenancy','word','(computing) one system instance serving many separate customers with their data kept isolated','kiến trúc đa khách thuê (một hệ thống phục vụ nhiều khách, dữ liệu tách biệt)','/ˌmʌlti ˈtenənsi/','c1','published','vault',datetime('now'),datetime('now')),
('myriad','word','extremely large in number','vô số, muôn vàn','/ˈmɪriəd/','c1','published','vault',datetime('now'),datetime('now')),
('necessitate','word','to make something necessary','đòi hỏi, buộc phải có','/nəˈsesɪteɪt/','c1','published','vault',datetime('now'),datetime('now')),
('negatively affect','collocation','to have a bad or harmful influence on something','ảnh hưởng tiêu cực',NULL,NULL,'published','vault',datetime('now'),datetime('now')),
('the odds-on favourite','idiom','the one most expected to win','ứng viên sáng giá nhất',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('an order of magnitude','collocation','a factor of ten','một bậc (gấp mười lần)',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('oversight','word','two opposite senses — see below','tuỳ nghĩa (xem bên dưới)','/ˈəʊvəsaɪt/','c1','published','vault',datetime('now'),datetime('now')),
('paradox','word','a self-contradictory thing that turns out to be true; or a person of odd contradictions','nghịch lý','/ˈpærədɒks/','b2','published','vault',datetime('now'),datetime('now')),
('paradoxical','word','contradictory and yet true','nghịch lý (tính từ)','/ˌpærəˈdɒksɪkl/','c1','published','vault',datetime('now'),datetime('now')),
('to pin traffic','collocation','to route traffic to a specific target and hold it there instead of letting it move','ghim traffic vào một đích cố định','/pɪn/','c1','published','vault',datetime('now'),datetime('now')),
('primitive','word','very simple or belonging to an early stage of development; (computing) a basic building block','thô sơ, sơ khai; (trong lập trình) khối xây dựng cơ bản','/ˈprɪmətɪv/','c1','published','vault',datetime('now'),datetime('now')),
('prominent','word','important or well known','nổi bật, có tiếng nói','/ˈprɒmɪnənt/','c1','published','vault',datetime('now'),datetime('now')),
('prong','word','each point of a fork; each separate part of an attack or an argument','mũi nhọn (của nĩa); nhánh (của một kế hoạch)','/prɒŋ/','c2','published','vault',datetime('now'),datetime('now')),
('put something in place','collocation','to set something up so that it is ready and working','thiết lập, đưa vào vận hành','/pʊt ɪn ˈpleɪs/','b2','published','vault',datetime('now'),datetime('now')),
('rake','word','a tool with a long handle and a row of points, used for gathering or levelling','cái cào; cào, san phẳng','/reɪk/','c2','published','vault',datetime('now'),datetime('now')),
('read between the lines','idiom','to look for or discover a meaning in something that is not openly stated','đọc hiểu ẩn ý, hiểu điều người ta không nói thẳng','/ˌriːd bɪtwiːn ðə ˈlaɪnz/','b2','published','vault',datetime('now'),datetime('now')),
('reason','word','the capacity for logic','lý trí (NOT lý do)','/ˈriːzn/','b1','published','vault',datetime('now'),datetime('now')),
('rebound','word','a bouncing back; the portion of an efficiency saving that gets eaten back by extra use','hiệu ứng bật lại','/ˈriːbaʊnd/ (noun) · /rɪˈbaʊnd/ (verb)','c1','published','vault',datetime('now'),datetime('now')),
('recreational activity','collocation','an activity done for enjoyment or leisure when one is not working','hoạt động giải trí, vui chơi','/ˌrekriˈeɪʃənl/',NULL,'published','vault',datetime('now'),datetime('now')),
('regulator','word','a person or official body that supervises a particular industry or public activity','nhà quản lý, cơ quan quản lý','/ˈreɡjuleɪtə(r)/','c1','published','vault',datetime('now'),datetime('now')),
('reiterate','word','to repeat something you have already said, especially to emphasize it','nhắc lại (điều đã nói) để nhấn mạnh','/riˈɪtəreɪt/','c1','published','vault',datetime('now'),datetime('now')),
('relieve somebody of something','phrasal-verb','three senses — see below','tuỳ nghĩa (xem bên dưới)','relieve /rɪˈliːv/','c1','published','vault',datetime('now'),datetime('now')),
('relieved','word','feeling happy because something unpleasant has stopped or has not happened','nhẹ nhõm, thở phào','/rɪˈliːvd/','b2','published','vault',datetime('now'),datetime('now')),
('require','word','to need','yêu cầu; cần','/rɪˈkwaɪə/','b1','published','vault',datetime('now'),datetime('now')),
('resign','word','to quit a job formally','từ chức; xin nghỉ việc','/rɪˈzaɪn/','b2','published','vault',datetime('now'),datetime('now')),
('retain','word','to keep or hold on to','giữ lại','/rɪˈteɪn/','b2','published','vault',datetime('now'),datetime('now')),
('root for the underdog','idiom','to support the weaker side','ủng hộ kẻ yếu thế',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('root for','phrasal-verb','to support; to cheer for','ủng hộ; cổ vũ','/ˈruːt fɔː/','b2','published','vault',datetime('now'),datetime('now')),
('runaway degradation','collocation','performance getting worse in a self-reinforcing loop that cannot be stopped from inside','suy giảm mất kiểm soát (càng lúc càng tệ, tự khuếch đại)','runaway /ˈrʌnəweɪ/ · degradation /ˌdeɡrəˈdeɪʃn/','c1','published','vault',datetime('now'),datetime('now')),
('runway','word','the strip an aircraft takes off from; (business) how long your money lasts before it runs out','đường băng; (kinh doanh) thời gian tiền còn đủ dùng','/ˈrʌnweɪ/','b2','published','vault',datetime('now'),datetime('now')),
('safeguard','word','something designed to protect people from harm, risk or danger','biện pháp bảo vệ, cơ chế phòng ngừa','/ˈseɪfɡɑːd/','c1','published','vault',datetime('now'),datetime('now')),
('say as much','idiom','to say exactly that, without necessarily using those words','nói đúng ý đó (dù không dùng nguyên văn)','much /mʌtʃ/','c1','published','vault',datetime('now'),datetime('now')),
('shadowing','word','(computing) sending a copy of real traffic to a new system to compare its results without using them','chạy song song để đối chiếu (gửi bản sao traffic thật sang hệ mới, không dùng kết quả)','/ˈʃædəʊɪŋ/','c1','published','vault',datetime('now'),datetime('now')),
('signal-boost','word','to spread someone else''s message so that more people see it','khuếch đại, lan toả giúp thông điệp của người khác','/ˈsɪɡnəl buːst/','c1','published','vault',datetime('now'),datetime('now')),
('sleep around','phrasal-verb','to have sex with a lot of different people','ngủ lang, quan hệ với nhiều người','/ˌsliːp əˈraʊnd/','b2','published','vault',datetime('now'),datetime('now')),
('soak','word','to put something in liquid for a time so that it becomes completely wet','ngâm (trong nước)','/səʊk/','c1','published','vault',datetime('now'),datetime('now')),
('spend time','collocation','to use time on something','dành thời gian',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('sprout','word','(of a plant or seed) to produce new leaves or roots; to start to grow','nảy mầm; mầm cây','/spraʊt/','c2','published','vault',datetime('now'),datetime('now')),
('squeeze as much juice out of something','idiom','to extract every last bit of value or performance from something you already have','vắt kiệt giá trị từ cái đang có','juice /dʒuːs/','c1','published','vault',datetime('now'),datetime('now')),
('staggering','word','so great, shocking or surprising that it is difficult to believe','gây choáng, khủng khiếp (về mức độ)','/ˈstæɡərɪŋ/','c1','published','vault',datetime('now'),datetime('now')),
('stalled processing','collocation','processing that has stopped making progress without having failed','xử lý bị khựng lại (dừng tiến độ nhưng chưa chết)','stall /stɔːl/','c2','published','vault',datetime('now'),datetime('now')),
('starch','word','a white carbohydrate food substance found in potatoes, flour, rice and grain','tinh bột','/stɑːtʃ/','c2','published','vault',datetime('now'),datetime('now')),
('steep','word','to leave something in a liquid for some time so that it softens or takes in the taste','ngâm (ngũ cốc, thực phẩm) trong chất lỏng','/stiːp/','b2','published','vault',datetime('now'),datetime('now')),
('step down','phrasal-verb','to leave a senior position','từ chức (vị trí cấp cao)','/ˌstep ˈdaʊn/','b2','published','vault',datetime('now'),datetime('now')),
('step out','phrasal-verb','to leave work briefly','ra ngoài một lát','/ˌstep ˈaʊt/','b1','published','vault',datetime('now'),datetime('now')),
('stick to','phrasal-verb','to limit yourself to something','chỉ dùng; bám vào','/ˈstɪk tuː/','b1','published','vault',datetime('now'),datetime('now')),
('stifle','word','two senses — see below','tuỳ nghĩa (xem bên dưới)','/ˈstaɪfl/','c1','published','vault',datetime('now'),datetime('now')),
('be stretched to the limit','collocation','to have your resources used so heavily that there is nothing left spare','bị căng hết mức, dùng tới giới hạn','/stretʃt/','b2','published','vault',datetime('now'),datetime('now')),
('subculture','word','a smaller culture inside a bigger one','tiểu văn hoá','/ˈsʌbkʌltʃə/','b2','published','vault',datetime('now'),datetime('now')),
('substantial','word','large in amount, value or importance','đáng kể, lớn','/səbˈstænʃl/','c1','published','vault',datetime('now'),datetime('now')),
('surveillance','word','close observation or monitoring, especially via security cameras','sự giám sát, sự theo dõi','/sɜːˈveɪləns/','c1','published','vault',datetime('now'),datetime('now')),
('susceptible','word','very likely to be influenced, harmed or affected by something','dễ bị ảnh hưởng, dễ mắc phải','/səˈseptəbl/','c1','published','vault',datetime('now'),datetime('now')),
('suture','word','a stitch or row of stitches holding together the edges of a wound or surgical incision','mũi khâu, vết khâu','/ˈsuːtʃə(r)/',NULL,'published','vault',datetime('now'),datetime('now')),
('testify','word','to state formally that something is true, especially as a witness in court','làm chứng, khai (trước toà)','/ˈtestɪfaɪ/','c1','published','vault',datetime('now'),datetime('now')),
('the same X as Y','collocation','the fixed comparison frame for sameness','giống như',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('three-pronged','word','having three separate parts or lines of attack','gồm ba mũi, ba hướng','/ˌθriː ˈprɒŋd/','c2','published','vault',datetime('now'),datetime('now')),
('throw caution to the wind(s)','idiom','to stop caring about how dangerous something might be; to start taking risks','bất chấp rủi ro, liều','caution /ˈkɔːʃn/','c1','published','vault',datetime('now'),datetime('now')),
('transcription','word','the written phonetic form of a word','phiên âm','/trænˈskrɪpʃn/','b2','published','vault',datetime('now'),datetime('now')),
('trial','word','a formal examination of evidence in court to decide whether somebody is guilty','phiên toà, vụ xét xử; cuộc thử nghiệm','/ˈtraɪəl/','b2','published','vault',datetime('now'),datetime('now')),
('turn out','phrasal-verb','to be revealed, in the end','hoá ra','/ˌtɜːn ˈaʊt/','b2','published','vault',datetime('now'),datetime('now')),
('ulterior','word','(of a reason) kept hidden and not admitted','(động cơ) giấu kín, không nói ra','/ʌlˈtɪəriə(r)/','c1','published','vault',datetime('now'),datetime('now')),
('an underdog story / spirit','collocation','nouns that naturally follow *underdog*','câu chuyện/tinh thần của kẻ yếu thế',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('underdog','word','the one expected to lose','kẻ yếu thế; cửa dưới','/ˈʌndədɒɡ/','b2','published','vault',datetime('now'),datetime('now')),
('unmet demand','collocation','demand that exists but is not currently being served','nhu cầu chưa được đáp ứng',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('unprecedented','word','that has never happened, been done or been known before','chưa từng có tiền lệ','/ʌnˈpresɪdentɪd/','c1','published','vault',datetime('now'),datetime('now')),
('vandal','word','a person who deliberately destroys or damages property','kẻ phá hoại của công','/ˈvændl/','b2','published','vault',datetime('now'),datetime('now')),
('vandalize','word','deliberately destroy or damage public or private property','phá hoại của công','/ˈvændəlaɪz/','c1','published','vault',datetime('now'),datetime('now')),
('wager','word','an arrangement to risk money on the result of an event; a bet','vụ cá cược; sự đánh cược','/ˈweɪdʒə(r)/','c1','published','vault',datetime('now'),datetime('now')),
('walk me through','conversational','explain it to me step by step','giải thích từng bước cho tôi',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('a walking paradox','idiom','a person full of contradictions','con người đầy mâu thuẫn',NULL,'c1','published','vault',datetime('now'),datetime('now')),
('washback','word','the large vessel in which wort is fermented into a beer-like liquid','thùng lên men (trong nhà máy whisky)',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('be well acquainted with something','collocation','to know something thoroughly from having read, seen or experienced it','rất quen thuộc, nắm rõ (do đã trải qua)','/əˈkweɪntɪd/','c1','published','vault',datetime('now'),datetime('now')),
('what I was after','conversational','what I actually wanted','điều tôi thực sự muốn',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('with ease','idiom','without difficulty or effort','một cách dễ dàng','/iːz/','c1','published','vault',datetime('now'),datetime('now')),
('without a hitch','idiom','with no problems at all','suôn sẻ; không trục trặc gì','hitch /hɪtʃ/','b2','published','vault',datetime('now'),datetime('now')),
('witness','word','a person who saw something happen, or who gives evidence in court; to see something happen','nhân chứng; chứng kiến','/ˈwɪtnəs/','b2','published','vault',datetime('now'),datetime('now')),
('wort','word','the sweet liquid drawn off the mash, before yeast turns it into alcohol','dịch đường (nước ngọt rút ra từ mash, trước khi lên men)',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('yeast','word','a fungus used in making beer and wine, or to make bread rise','men, nấm men','/jiːst/','c2','published','vault',datetime('now'),datetime('now')),
('zealot','word','an uncompromising fanatic','kẻ cuồng tín','/ˈzelət/','c1','published','vault',datetime('now'),datetime('now')),
('X-wise','grammar-pattern',NULL,'Thêm -wise vào danh từ để tạo trạng từ thân mật, nghĩa là *xét về mặt X*.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('do you mind + -ing','grammar-pattern',NULL,'*mind* đi với V-ing, không đi với *to V*.',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('don''t let X fool you','grammar-pattern',NULL,'*let* + tân ngữ + động từ nguyên mẫu không *to*.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('emphatic do','grammar-pattern',NULL,'Dùng *do/does/did* + động từ nguyên mẫu để nhấn mạnh điều đó là thật.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('from X to Y','grammar-pattern',NULL,'Không thêm *become*; cặp idiom chặt thì bỏ mạo từ.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('go ahead and + base verb','grammar-pattern',NULL,'*go ahead and* + động từ nguyên mẫu = cứ làm đi, không cần xin phép.',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('go off + to + base verb','grammar-pattern',NULL,'Sau *to* dùng động từ nguyên thể.',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('past as a preposition','grammar-pattern',NULL,'*past* làm giới từ = vượt quá.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('turn out to be / turn out that','grammar-pattern',NULL,'Không bao giờ dùng bị động với *turn out*.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('whose vs who''s','grammar-pattern',NULL,'*whose* sở hữu; *who''s* = who is. Phát âm giống hệt nhau.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('-ate ending vowel shift','pronunciation-rule',NULL,'Từ đuôi -ate: động từ đọc /-eɪt/, tính từ hoặc danh từ đọc /-ət/. Trọng âm không đổi.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('Compound noun stress','pronunciation-rule',NULL,'Danh từ ghép: nhấn phần đầu.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('Noun and verb stress shift','pronunciation-rule',NULL,'Danh từ nhấn âm đầu, động từ nhấn âm sau.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('Stress shift with -ical','pronunciation-rule',NULL,'Thêm *-ical* làm dịch chuyển trọng âm.',NULL,'b2','published','vault',datetime('now'),datetime('now')),
('Bare fragments with no main verb','error-drill',NULL,'Mỗi câu cần chủ ngữ và động từ chính chia thì.',NULL,NULL,'published','vault',datetime('now'),datetime('now')),
('Comma splices','error-drill',NULL,'Không nối hai câu hoàn chỉnh bằng dấu phẩy. Dùng dấu chấm, chấm phẩy, hoặc phẩy + liên từ.',NULL,NULL,'published','vault',datetime('now'),datetime('now')),
('Mid-sentence capital letters','error-drill',NULL,'Chỉ viết hoa sau dấu chấm hoặc với danh từ riêng.',NULL,NULL,'published','vault',datetime('now'),datetime('now')),
('Missing articles before singular countable nouns','error-drill',NULL,'Danh từ đếm được số ít luôn cần mạo từ.',NULL,NULL,'published','vault',datetime('now'),datetime('now')),
('Noun used as adjective','error-drill',NULL,'Trước danh từ hoặc sau *be / very / so* phải dùng tính từ, không dùng danh từ.',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('Past question with did','error-drill',NULL,'Hỏi về việc đã xảy ra thì dùng *did* + động từ nguyên mẫu, không dùng hiện tại đơn.',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('Preposition plus -ing','error-drill',NULL,'Sau giới từ, động từ phải ở dạng -ing.',NULL,'b1','published','vault',datetime('now'),datetime('now')),
('Third-person singular -s','error-drill',NULL,'Chủ ngữ số ít ở thì hiện tại đơn thì động từ thêm -s.',NULL,NULL,'published','vault',datetime('now'),datetime('now'))
ON CONFLICT (term, kind) DO NOTHING;
